direction: right

title: Web App {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}

BrowserA: {
  label: Browser
  DOM Tree: {
    shape: image
    icon: https://icons.terrastruct.com/tech%2Fbrowser-2.svg
  }
  Wasabi: {
    shape: image
    icon: https://icons.terrastruct.com/dev%2Fjavascript.svg
  }
  DOM Tree -> Wasabi: Event
  Dom Tree <- Wasabi: Patch
}

BrowserB: {
  label: Browser
  DOM Tree: {
    shape: image
    icon: https://icons.terrastruct.com/tech%2Fbrowser-2.svg
  }
  Wasabi: {
    shape: image
    icon: https://icons.terrastruct.com/dev%2Fjavascript.svg
  }
  DOM Tree -> Wasabi: Event
  Dom Tree <- Wasabi: Patch
}

Server: {
  Wasabi: {
    GroupA: {
      label: Goroutine
      style.stroke-dash: 5
      style.border-radius: 8
      WebSocket Handler: {
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fgo.svg
      }
      State: {
        label: State
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F117-database.svg
      }
      "WebSocket Handler" <-> State
    }

    GroupB: {
      label: Goroutine
      style.stroke-dash: 5
      style.border-radius: 8
      WebSocket Handler: {
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fgo.svg
      }
      State: {
        label: State
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F117-database.svg
      }
      "WebSocket Handler" <-> State
    }
  }
}

BrowserA.Wasabi -> Server.Wasabi.GroupA."WebSocket Handler": Event
BrowserA.Wasabi <- Server.Wasabi.GroupA."WebSocket Handler": DOM Diff

BrowserB.Wasabi -> Server.Wasabi.GroupB."WebSocket Handler": Event
BrowserB.Wasabi <- Server.Wasabi.GroupB."WebSocket Handler": DOM Diff
